# Generated by Django 2.0.3 on 2021-07-02 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200422_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
